# Generated by Django 3.2.3 on 2021-05-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=50, null=True)),
                ('streetAddress', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('phoneNumber1', models.CharField(max_length=20)),
                ('phoneNumber2', models.CharField(blank=True, max_length=20, null=True)),
                ('dateJoined', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, max_length=25, null=True)),
                ('gst', models.CharField(blank=True, max_length=30, null=True)),
                ('licenseno', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
